# Generated by Django 2.1 on 2020-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_pic1',
            field=models.ImageField(default='default.jpg', upload_to='project_pics'),
        ),
    ]
