# Generated by Django 2.1 on 2020-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_project_pic1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vid_src',
            field=models.CharField(default='nothing_yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_pic1',
            field=models.ImageField(upload_to='project_pics'),
        ),
    ]
