# Generated by Django 2.1 on 2020-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200420_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vid_src',
            field=models.CharField(default='https://www.youtube.com/embed/', max_length=100),
        ),
    ]
